apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260507-224645-3brxvvv2xbzb-service
spec:
  selector:
    app: enterprise-system-20260507-224645-3brxvvv2xbzb
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
